import { Select, Space, Typography, Divider, Form, InputNumber, Button, DatePicker, message } from 'antd';
import { useState } from 'react';
import { useCrypto } from '../context/crypto-context';

export default function AddAssetForm({ onClose }) {
  const { crypto } = useCrypto(); const [coin, setCoin] = useState(null); const [form] = Form.useForm();
  const onFinish = () => { message.success(`${coin.name} added to your portfolio`); form.resetFields(); onClose?.(); };
  if (!coin) return <div><Typography.Paragraph style={{ color: '#8991ac' }}>Choose an asset to start tracking its performance.</Typography.Paragraph><Select autoFocus showSearch style={{ width: '100%' }} onSelect={(value) => setCoin(crypto.find((item) => item.id === value))} placeholder="Search coins" options={crypto.map((item) => ({ label: item.name, value: item.id, icon: item.icon, symbol: item.symbol }))} optionRender={(option) => <Space><img className="coin-icon" src={option.data.icon} alt="" style={{ width: 25, height: 25 }} />{option.data.label}<span className="coin-symbol">{option.data.symbol}</span></Space>} /></div>;
  return <Form form={form} className="form-shell" layout="vertical" onFinish={onFinish}><div className="coin-line"><img className="coin-icon" src={coin.icon} alt="" /><Typography.Title level={3} style={{ margin: 0, color: '#fff' }}>{coin.name} <span className="coin-symbol">{coin.symbol}</span></Typography.Title></div><Divider /><Form.Item label="Amount" name="amount" rules={[{ required: true, message: 'Enter the amount' }]}><InputNumber min={0} style={{ width: '100%' }} placeholder="0.00" /></Form.Item><Form.Item label="Purchase price" name="price" rules={[{ required: true, message: 'Enter the purchase price' }]}><InputNumber min={0} style={{ width: '100%' }} addonAfter="$" placeholder={coin.price.toFixed(2)} /></Form.Item><Form.Item label="Purchase date" name="date" rules={[{ required: true, message: 'Choose a date' }]}><DatePicker showTime style={{ width: '100%' }} /></Form.Item><Button type="primary" htmlType="submit" block className="primary-btn">Add position</Button></Form>;
}
